services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - server/.docker.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - nest-network

  db:
    image: postgres:15
    container_name: database
    restart: unless-stopped
    environment:
      - server/.docker.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nest-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - nest-network

networks:
  nest-network:

volumes:
  pg_data:
